name: Auto Merge Dependabot Pull Requests
on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Wait for checks to complete
      run: |
        # Wait for all checks to complete before proceeding
        while [ "$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/check-suites | jq -r '.check_suites[].conclusion' | grep -c -v 'success')" -ne 0 ]; do
          echo "Waiting for checks to complete..."
          sleep 10
        done

    - name: Auto merge Dependabot pull requests
      run: |
        # Check if the pull request is from Dependabot
        if [[ ${{ github.event.pull_request.user.login }} == 'dependabot[bot]' ]]; then
          # Merge the pull request
          git fetch origin pull/${{ github.event.pull_request.number }}/head:dependabot_branch
          git checkout dependabot_branch
          git merge --no-ff ${{ github.event.pull_request.head.sha }}
          git push origin HEAD:${{ github.event.pull_request.base.ref }}
        else
          echo "This pull request is not from Dependabot. Skipping auto-merge."
        fi
