name: Label PR on Approvals

on:
  pull_request_review:
    types:
      - submitted

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check approvals and label PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;

            try {
              const octokit = new github.getOctokit(context.token);
              const reviews = await octokit.pulls.listReviews({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              });

              const requiredApprovals = 3;

              if (reviews.data.length >= requiredApprovals) {
                await octokit.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: prNumber,
                  labels: ['Kvalitetssikring er gjennomført'],
                });
              }
            } catch (error) {
              console.error('Error accessing GitHub API:', error.message);
              process.exit(1);
            }
